### ISSUE TITLE
Hey Usama send me that Lazagne FUD

### ISSUE THREAD

**Issue by codings9** [usama7628674/pymail#1]
Hey Usama send me that Lazagne FUD
Email:
donaldtrumptwitterfingers@gmail.com
You can even share the link using Google drive.
I would love to do a video on that~MunYa!

**Comment by usama7628674** [comment]
@codings9 Are you available on discord?We can chat there and I'll share my research and you share yours.

**Comment by usama7628674** [comment]
@codings9 Here's the result  https://antiscan.me/scan/new/result?id=aAg1fPGvr3cL.
I used string obfuscation you know replacing "lazagnge" with "usama" and turned it into FUD.

**Comment by codings9** [comment]
lol, this is my second request for discord-i looked up discord.
But i was  not motivated to get in on that action.

Can you pease enlighten me?

Why discord?
And why do you use it?
Lol....
Or whats so special about it?

**Comment by usama7628674** [comment]
@codings9 Check your mail i just sent you lazagne

**Comment by codings9** [comment]
Okay, lol that’s what i did with Empire😉to bypass av

**Comment by usama7628674** [comment]
@codings9 Add me on discord usama sattar#0670

**Comment by usama7628674** [comment]
@codings9 Discord is used by many users who are into hacking.Its a good platform you can create dedicate servers and channels.

**Comment by codings9** [comment]
https://discord.gg/wKePUt

**Comment by anomydarklord** [comment]
> @codings9 Check your mail i just sent you lazagne

Hey frd please send me Lazagne Fud at
anomydarklord@gmail.com
